name: tide_kit
description: "Tide Kit is a toolkit for building IDE and studio like apps on all platforms using Flutter."
version: 1.2.0
repository: https://github.com/larryaasen/tide/tree/main/packages/tide_kit
homepage: https://github.com/larryaasen/tide/tree/main/packages/tide_kit
screenshots:
  - description: 'Tide Example'
    path: doc/tide_example_3.png

environment:
  sdk: ^3.5.0
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.1
  get_it: ^8.0.2
  os_detect: ^2.0.1
  uuid: '>=3.0.5 <5.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: '>=4.0.0 <6.0.0'

flutter:
